backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "hero_heading", widget: "string"}
          - {label: "Hero Subheading", name: "hero_subheading", widget: "text"}
          - {label: "Mission Statement", name: "mission_statement", widget: "markdown"}
          - label: "Core Principles"
            name: "core_principles"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Donation Section"
            name: "donation_section"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Subheading", name: "subheading", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Author", name: "author", widget: "string"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
  
  - name: "settings"
    label: "Settings"
    files:
      - file: "site_settings.json"
        label: "Site Settings"
        name: "settings"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - label: "Social Media"
            name: "social_media"
            widget: "list"
            fields:
              - {label: "Platform", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - {label: "Contact Email", name: "contact_email", widget: "string", required: false}
          - {label: "Contact Phone", name: "contact_phone", widget: "string", required: false}
